ScreenManager:

  # main.py / home_screen.kv
  Main_Menu:


<Main_Menu>:
  MDFloatLayout:
    MDLabel:
      
    MDFillRoundFlatIconButton:
      text: "Start"
      icon: "controller"
      text_color: "black"
      icon_color: "red"
      size_hint: 0.3,0.09
      pos_hint: {"center_x":.500, "center_y":.300}

    MDLabel:
      text: "author: DuduArts"
      size_hint: 0.11, 0.1
      pos_hint: {"center_x":.520, "center_y":.100}
